[workspace]
members = [
    "crates/application",
    "crates/ocr",
    "crates/overlay",
    "crates/shared",
    "crates/wf-info",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
shared = { path = "crates/shared" }
application = { path = "crates/application" }
ocr = { path = "crates/ocr" }
overlay = { path = "crates/overlay" }
ashpd = { version = "0.13", default-features = false, features = ["async-io", "global_shortcuts", "screencast", "screenshot"] }
async-io = "2"
env_logger = "0.11"
futures-util = "0.3"
iced = { version = "0.13", features = ["tokio", "image"] }
iced_layershell = "0.13"
image = "0.25"
kreuzberg-tesseract = "4.9"
log = "0.4"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.9"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "unstable"] }
